---
title: "Migration circle diagram"
output:
  html_document:
    df_print: paged
    code_download: true
---

```{r setup}
library(circlize)
library(tidyverse)
library(gt)
library(skimr)
```

```{r source data prep script}
source("01_prep-data.R")
```


Načíst data

```{r source colour script}
source("02_prep-colours.R")
df <- read_rds("data-processed/orig-dest-new.rds")
```

Upravit data

```{r filter data}
dfl <- df %>% 
  filter(value > 0) %>% 
  drop_na() %>% 
  select(from = origin, to = destination, value)
```


```{r check data}
dfl
```

Zkontrolovat, jestli jsou řádky unikátní 

```{r check unique}
distinct(dfl, from, to)
```

Počet řádků stejný, jako u konečného datasetu, takže fajn.

Vykreslit graf:

```{r chart-orig}
circos.clear()
chordDiagram(df)
```


Hmm, to vypadá fakt divně a nevím proč. Zkusíme funkci stavěnou na data frame, ne na matici:

```{r}
circos.clear()
chordDiagramFromDataFrame(dfl, directional = 1)
```


```{r filter chords}
dfl_filtered <- dfl %>% 
  ungroup() %>% 
  filter(value > 5e4) %>% 
  mutate(value = value/1e5,
         # to = str_replace(to, "Europe", "čáěšžěšéí"),
         # from = str_replace(from, "Europe", "čáěšžěšéí"),
         from = str_replace(from, "South-eastern Asia", "SouthEastern Asia") %>%
           str_wrap(10),
         to = str_replace(to, "South-eastern Asia", "SouthEastern Asia") %>% 
           str_wrap(10))
dfl_filtered
```


```{r}
setdiff(dfl_filtered$from, dfl_filtered$to)
setdiff(dfl_filtered$to, dfl_filtered$from)
```

```{r}
scales::show_col(cols, borders = F)
```

```{r}
names(cols)
```


```{r order}
nazevnik <- tribble(~ordered_en, ~ordered_cz, ~color_old, ~color,
                    "Eastern Africa","Východní Afrika","darkgreen",cols[["yellow"]],
                    "Middle Africa","Střední Afrika","chartreuse4",cols[["yellow_l"]],
                    "Northern Africa","Severní Afrika","chartreuse3",cols[["orange"]],
                    "Southern Africa","Jižní Afrika","darkolivegreen",cols[["orange_l"]],
                    "Western Africa","Západní Afrika","darkolivegreen3","#e6bd33",
                    "Central Asia","Střední Asie","blue4",cols[["blue_dark"]],
                    "Eastern Asia","Východní Asie","blue1",cols[["blue_dark_l"]],
                    "Southern Asia","Jižní Asie","cornflowerblue",cols[["blue_light_l"]],
                    "SouthEastern Asia","Jihovýchodní Asie","blue1",cols[["blue_light"]],
                    "Western Asia","Západní Asie","deepskyblue","#023FA5",
                    "Eastern Europe","Východní Evropa","brown3",cols[["brown_l"]],
                    "Northern Europe","Severní Evropa","brown1",cols[["brown"]],
                    "Southern Europe","Jižní Evropa","coral",cols[["purple"]],
                    "Western Europe","Západní Evropa","darkred",cols[["purple_l"]],
                    "Caribbean","Karibik","blueviolet",cols[["wine"]],
                    "Central America","Střední Amerika","darkmagenta",cols[["green_l"]],
                    "South America","Jižní Amerika","darkorchid2","#006600",
                    "Northern America","Severní Amerika","darksalmon",cols[["green"]],
                    "Oceania","Oceánie","deeppink3", cols[["wine_l"]]) %>% 
  mutate(label_wrapped_en = str_wrap(ordered_en, 10),
         label_wrapped_cz = str_wrap(ordered_cz, 10))

setdiff(nazevnik$label_wrapped_en, dfl_filtered$from)
setdiff(dfl_filtered$from, nazevnik$label_wrapped_en)
setdiff(dfl_filtered$to, nazevnik$label_wrapped_en)

```

```{r}
length(unique(nazevnik$label_wrapped_cz)) == length(nazevnik$label_wrapped_cz)
```


```{r plotting function}
# from https://stackoverflow.com/questions/31943102/rotate-labels-in-a-chorddiagram-r-circlize
make_circle_plot <- function(cz = FALSE) {
  
  barvy_grid <- nazevnik$color
  
  names(barvy_grid) <- if(cz) nazevnik$label_wrapped_cz else
    nazevnik$label_wrapped_en
  
  barvy_links <- dfl_filtered %>% 
    left_join(nazevnik %>% rename(from = label_wrapped_en)) %>% 
    pull(color)
  
  if(cz) {
    plot_data <- dfl_filtered %>% 
      left_join(nazevnik %>% select(from = label_wrapped_en, 
                                    label_wrapped_cz)) %>% 
      select(-from) %>%
      rename(from = label_wrapped_cz) %>% 
      left_join(nazevnik %>% select(to = label_wrapped_en,
                                    label_wrapped_cz)) %>% 
      select(-to) %>%
      rename(to = label_wrapped_cz) %>% 
      select(to, from, value)
  } else {
    plot_data <- dfl_filtered %>% 
      select(to, from, value)
  }
  
  # print(plot_data)
  
  order_list <- if(cz) {nazevnik$label_wrapped_cz
  } else {
    nazevnik$label_wrapped_en
  }
  
  # plot_data$to %in% order_list
  # plot_data$from %in% order_list
  
  arrow_order <- 34
  
  par(lheight = .8)
  chordDiagramFromDataFrame(plot_data,
                            directional = -1,
                            diffHeight = uh(-3, "mm"),
                            link.arr.type = "triangle",
                            link.arr.width = .30,
                            link.arr.length = .30,
                            link.arr.lwd = 2,
                            # link.arr.col = barvy_links,
                            link.arr.col = c(rep(NA, arrow_order),
                                             "#023FA5",
                                             rep(NA, nrow(plot_data)-1-arrow_order)),
                            direction.type = "arrows+diffHeight",
                            grid.col = barvy_grid,
                            col = barvy_links,
                            transparency = .2,
                            link.lwd = 2,
                            link.border = "white",
                            order = order_list,
                            annotationTrack = "grid",
                            preAllocateTracks = 1)
  circos.trackPlotRegion(track.index = 1, panel.fun = function(x, y) {
    xlim = get.cell.meta.data("xlim")
    ylim = get.cell.meta.data("ylim")
    sector.name = get.cell.meta.data("sector.index")
    circos.text(mean(xlim), ylim[1] + .4, sector.name,
                facing = "clockwise", niceFacing = TRUE, adj = c(0, 0.5))
    circos.axis(h = "top", labels.cex = 0.5, major.tick.percentage = 0.2,
                sector.index = sector.name, track.index = 2, minor.ticks = 4)
  }, bg.border = NA)
  
  # return(plot_data)
}
make_circle_plot(cz = FALSE)
```


```{r plot-en}
cairo_pdf(file = "chart-output/circle_en.pdf", width = 8, height = 8)
make_circle_plot(cz = FALSE)
dev.off()
make_circle_plot(cz = FALSE)
```

```{r plot-cz}
cairo_pdf(file = "chart-output/circle_cz.pdf", width = 8, height = 8)
make_circle_plot(cz = TRUE)
dev.off()
make_circle_plot(cz = TRUE)
```

## Rozdíly mezi verzemi

```{r}
source("98_use-preprocessed-data.R")

compar <- dfl_filtered %>% 
  mutate(flow = paste(to, "to", from)) %>% 
  select(-from, -to) %>% 
  full_join(dflo_filtered %>% 
              mutate(flow = paste(from, "to", to)) %>% 
              select(-from, -to, value_old = value)
  ) %>% 
  replace_na(replace = list(value = 0, value = 0)) %>% 
  select(flow, value_old, value) %>% 
  mutate(diff = value - value_old,
         diff_pct = diff/value) %>% 
  arrange(desc(abs(diff_pct)))
compar
```


```{r}
compar %>% 
  gt::gt() %>% 
  fmt_number(2:4, decimals = 1) %>% 
  fmt_percent(5, decimals = 1)
```


